/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscenarioRouteImport } from './routes/escenario'
import { Route as HabilidadesRouteImport } from './routes/habilidades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscenarioRoute = EscenarioRouteImport.update({
  id: '/escenario',
  path: '/escenario',
  getParentRoute: () => rootRouteImport,
} as any)
const HabilidadesRoute = HabilidadesRouteImport.update({
  id: '/habilidades',
  path: '/habilidades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escenario': typeof EscenarioRoute
  '/habilidades': typeof HabilidadesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/escenario': typeof EscenarioRoute
  '/habilidades': typeof HabilidadesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/escenario': typeof EscenarioRoute
  '/habilidades': typeof HabilidadesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/escenario' | '/habilidades'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/escenario' | '/habilidades'
  id: '__root__' | '/' | '/escenario' | '/habilidades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EscenarioRoute: typeof EscenarioRoute
  HabilidadesRoute: typeof HabilidadesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escenario': {
      id: '/escenario'
      path: '/escenario'
      fullPath: '/escenario'
      preLoaderRoute: typeof EscenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habilidades': {
      id: '/habilidades'
      path: '/habilidades'
      fullPath: '/habilidades'
      preLoaderRoute: typeof HabilidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EscenarioRoute: EscenarioRoute,
  HabilidadesRoute: HabilidadesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
